### PR TITLE
Created Navbar Components

### LINKED ISSUE #17: Create Header Component
I'll like to take this on as the section of the site has a coming soon on it

### PR DESCRIPTION
**Pull request by Onyelaudochukwuka**
## 🛠️ Fixes Issue
closes #17 

## 👨‍💻 Changes proposed
- Added 12 new Navbars
- Removed the coming soon label

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

### CODE REVIEW

**Comment by khazifire** [comment]
@Onyelaudochukwuka since most of the headers are the same with the difference being only in the hamburger menu (you can consider removing some of them, since its just duplicates)

for instance (2 lines and 3 line hamburger , its the same thing), so i think you can just include the 3 lines since its the standard
and also consider adding hover effect on the nav items

Thank you

**Comment by Onyelaudochukwuka** [comment]
> @Onyelaudochukwuka since most of the headers are the same with the difference being only in the hamburger menu (you can consider removing some of them, since its just duplicates)
> 
> for instance (2 lines and 3 line hamburger , its the same thing), so i think you can just include the 3 lines since its the standard and also consider adding hover effect on the nav items
> 
> Thank you

Doing This right now

**Comment by akebu6** [comment]
@Onyelaudochukwuka kindly squash all commits into one as this is best for any production code in order to make the VC graph cleaner

**Comment by Onyelaudochukwuka** [comment]
Resolved all issues

**Comment by Onyelaudochukwuka** [comment]
closes #24  and #20

**Comment by khazifire** [comment]
@Onyelaudochukwuka im glad you were able to fix the error that were in your previous pull request, something just caught my eyes as I was reviewing your work.

its impressible but i think for components with nested elements, you can just create them normally instead of using json

e.g. you can create nav1, nav2 component  and then import them in the navbar file, that way it would be so much cleaner to update and modify later on

Thank you

**Pull request merged**
