### PR TITLE
feat: make mobile nav bar

### LINKED ISSUE #15: Make the nav bar responsive on mobile
Hemberger menu can be added on mobile

image

### PR DESCRIPTION
**Pull request by Dun-sin**
## 👨‍💻 Changes proposed
- Make mobile navbar
- create useClickOutside hook for when the rest of the page is clicked
- create useWindowsDimensions hook to check the view width

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

### CODE REVIEW

**Review by Dun-sin — COMMENTED** [review]
Seems fine, let me know what you think

**Comment by khazifire** [comment]
@Dun-sin Looks great, just a few miner details need to be fixed

- hamburger menu icon is not vertically centered
- since the menu will only have 3 items, it would be better if the menu height, could be made shorter

image

**Comment by Dun-sin** [comment]
But as you wish

**Comment by khazifire** [comment]
in that case, you can try making it like this

image

**Pull request merged**
