### PR TITLE
Created a new Header Component.

### PR DESCRIPTION
**Pull request by Elishaokon13**
• Created a New header Component

### CODE REVIEW

**Comment by khazifire** [comment]
@Elishaokon13 There seem to be some errors, 

on your localserver, run ---> **npm build** 
then try to fix the errors that come up

**Comment by Elishaokon13** [comment]
> @Elishaokon13 There seem to be some errors,
> 
> on your localserver, run ---> **npm build** then try to fix the errors that come up

Alright.

**Comment by khazifire** [comment]
@Elishaokon13 can you fix the error, then create another merger request, thank you

image

**Comment by Elishaokon13** [comment]
I have resolved all errors in the footer component.
 @khazifire

**Comment by khazifire** [comment]
@Elishaokon13 there is a still a minor error,
image

**Comment by Elishaokon13** [comment]
I've Fixed it.
Thank you

**Comment by Elishaokon13** [comment]
@khazifire Please am I open to creating more components that can be helpful?

**Pull request merged**
