### PR TITLE
Added some margin on the sides according to issue: #7

### LINKED ISSUE #7: Add some margin on the left and right side of the site.
It seems like there is no margin and padding at the left and right edges of the site. Add it to make it look good

### PR DESCRIPTION
**Pull request by DugarRishab**
This Pull request resolves issue #7 

- Margins were added to both the left and right side of the desktop view
- Mobile view was not affected
- The below screenshot shows the changes made
- Closes #7 

image

### CODE REVIEW

**Comment by DugarRishab** [comment]
@khazifire Can you please review this request and accept it.

**Comment by khazifire** [comment]
@DugarRishab will review it

**Comment by khazifire** [comment]
I will not be merging this to the main, because it did removed some parts of the layout.

In addition, that margin issue can simply be fixed in just one line of code. If you analyzed carefully the layout component, you will realize that the children are styled with a custom container. Changes can simple be made to that css file

image

image

**Comment by DugarRishab** [comment]
@khazifire as my understanding, some components might have been removed due to merging conflicts. And just becouse the solution to the issue was easy, doesn't mean my PR is bunk. Please stick to the proper process next time.

**Comment by khazifire** [comment]
@DugarRishab im sry if my comment was offensive, but i meant it in a positive way. And just to let you know your work was awesome, and me not merging it does not devalue your work

**Pull request closed without merging**
